{"uid":"9d55426966bcbda0","name":"test_search_flights_1_stop_4___DEL____BOM____25_12_2024____2_Stop__","fullName":"testcases.test_searchflights.TestSearchAndVerifyFilter#test_search_flights_1_stop_4___DEL____BOM____25_12_2024____2_Stop__","historyId":"cb965b49d65ea300604de77642d2ac9b","time":{"start":1713210029196,"stop":1713210064385,"duration":35189},"status":"failed","statusMessage":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stop(s)' != '2 Stop'\n- 2 Stop(s)\n?       ---\n+ 2 Stop\n\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stop(s)' != '2 Stop'\n- 2 Stop(s)\n?       ---\n+ 2 Stop\n\n\n-+ [2/2] +-","statusTrace":"self = <testcases.test_searchflights.TestSearchAndVerifyFilter testMethod=test_search_flights_1_stop_4___DEL____BOM____25_12_2024____2_Stop__>, goingfrom = 'DEL', goingto = 'BOM'\ndate = '25/12/2024', stops = '2 Stop'\n\n    @data(*Utils.read_data_from_csv(\"/Users/k-bhatt/PythonTestFrameworkDemo/testdata/tdatacsv.csv\"))\n    @unpack\n    def test_search_flights_1_stop(self,goingfrom, goingto, date, stops):\n        # Provide going from location\n        search_flight_result =  self.launchPage.searchFlights(goingfrom, goingto, date)\n    \n        # To handle dynamic scroll\n        # self.launchPage.page_scroll()\n        self.launchPage.wait_for_loading_indicator()\n        # self.launchPage.page_scroll_to_bottom()\n        self.launchPage.page_scroll()\n    \n        # Select the filter 1 stop\n        search_flight_result.filter_flights_by_stop(stops)\n    \n        # Verify that the filtered results show flights having only 1 stop\n        allstops = search_flight_result.get_search_flights_results()\n        self.log.info(len(allstops))\n    \n>       self.utilPage.assertListItemText(allstops, stops)\n\ntestcases/test_searchflights.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities/utils.py:16: in assertListItemText\n    self.assert_all()\nenv/lib/python3.11/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stop(s)' != '2 Stop'\nE   - 2 Stop(s)\nE   ?       ---\nE   + 2 Stop\nE   \nE   \nE   -+ [1/2] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stop(s)' != '2 Stop'\nE   - 2 Stop(s)\nE   ?       ---\nE   + 2 Stop\nE   \nE   \nE   -+ [2/2] +-","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"_unittest_setUpClass_fixture_TestSearchAndVerifyFilter","time":{"start":1713209896110,"stop":1713209896110,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"browser","time":{"start":1713209896110,"stop":1713209896110,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"url","time":{"start":1713209896110,"stop":1713209896110,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup","time":{"start":1713210024478,"stop":1713210029195,"duration":4717},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"class_setup","time":{"start":1713210029195,"stop":1713210029196,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: ++++ soft assert failure details follow below ++++\n\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nThe following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\n+----------------------+----------------------+----------------------+\n Failure 1 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stop(s)' != '2 Stop'\n- 2 Stop(s)\n?       ---\n+ 2 Stop\n\n\n-+ [1/2] +-\n\n+----------------------+----------------------+----------------------+\n Failure 2 (\"wrapper\" method)\n+----------------------+----------------------+----------------------+\nTraceback (most recent call last):\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\n    self.soft_assert(self.assertEqual, stop.text, value)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\n    self.utilPage.assertListItemText(allstops, stops)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\n    assert_method(*arguments, **keywords)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\n    raise self.failureException(msg)\nAssertionError: '2 Stop(s)' != '2 Stop'\n- 2 Stop(s)\n?       ---\n+ 2 Stop\n\n\n-+ [2/2] +-","statusTrace":"self = <testcases.test_searchflights.TestSearchAndVerifyFilter testMethod=test_search_flights_1_stop_4___DEL____BOM____25_12_2024____2_Stop__>, goingfrom = 'DEL', goingto = 'BOM'\ndate = '25/12/2024', stops = '2 Stop'\n\n    @data(*Utils.read_data_from_csv(\"/Users/k-bhatt/PythonTestFrameworkDemo/testdata/tdatacsv.csv\"))\n    @unpack\n    def test_search_flights_1_stop(self,goingfrom, goingto, date, stops):\n        # Provide going from location\n        search_flight_result =  self.launchPage.searchFlights(goingfrom, goingto, date)\n    \n        # To handle dynamic scroll\n        # self.launchPage.page_scroll()\n        self.launchPage.wait_for_loading_indicator()\n        # self.launchPage.page_scroll_to_bottom()\n        self.launchPage.page_scroll()\n    \n        # Select the filter 1 stop\n        search_flight_result.filter_flights_by_stop(stops)\n    \n        # Verify that the filtered results show flights having only 1 stop\n        allstops = search_flight_result.get_search_flights_results()\n        self.log.info(len(allstops))\n    \n>       self.utilPage.assertListItemText(allstops, stops)\n\ntestcases/test_searchflights.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities/utils.py:16: in assertListItemText\n    self.assert_all()\nenv/lib/python3.11/site-packages/softest/case.py:139: in assert_all\n    self.fail(''.join(failure_output))\nE   AssertionError: ++++ soft assert failure details follow below ++++\nE   \nE   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\nE   The following 2 failures were found in \"wrapper\" (utilities.utils.Utils):\nE   +----------------------+----------------------+----------------------+\nE    Failure 1 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stop(s)' != '2 Stop'\nE   - 2 Stop(s)\nE   ?       ---\nE   + 2 Stop\nE   \nE   \nE   -+ [1/2] +-\nE   \nE   +----------------------+----------------------+----------------------+\nE    Failure 2 (\"wrapper\" method)\nE   +----------------------+----------------------+----------------------+\nE   Traceback (most recent call last):\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/utilities/utils.py\", line 11, in assertListItemText\nE       self.soft_assert(self.assertEqual, stop.text, value)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/testcases/test_searchflights.py\", line 39, in test_search_flights_1_stop\nE       self.utilPage.assertListItemText(allstops, stops)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/ddt.py\", line 221, in wrapper\nE       return func(self, *args, **kwargs)\nE     File \"/Users/k-bhatt/PythonTestFrameworkDemo/env/lib/python3.11/site-packages/softest/case.py\", line 62, in soft_assert\nE       assert_method(*arguments, **keywords)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 873, in assertEqual\nE       assertion_func(first, second, msg=msg)\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 1253, in assertMultiLineEqual\nE       self.fail(self._formatMessage(msg, standardMsg))\nE     File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py\", line 703, in fail\nE       raise self.failureException(msg)\nE   AssertionError: '2 Stop(s)' != '2 Stop'\nE   - 2 Stop(s)\nE   ?       ---\nE   + 2 Stop\nE   \nE   \nE   -+ [2/2] +-","steps":[],"attachments":[{"uid":"3a813102f05b91af","name":"Screenshot on failure","source":"3a813102f05b91af.png","type":"image/png","size":241274},{"uid":"e8242a194e0b1171","name":"log","source":"e8242a194e0b1171.txt","type":"text/plain","size":329},{"uid":"a5b8d4ff2849b418","name":"stdout","source":"a5b8d4ff2849b418.txt","type":"text/plain","size":70}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"setup::0","time":{"start":1713210064563,"stop":1713210064674,"duration":111},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_unittest_setUpClass_fixture_TestSearchAndVerifyFilter::0","time":{"start":1713210064675,"stop":1713210064675,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"testcases"},{"name":"suite","value":"test_searchflights"},{"name":"subSuite","value":"TestSearchAndVerifyFilter"},{"name":"host","value":"PC2368"},{"name":"thread","value":"16948-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.test_searchflights"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"c3ac684b59e209da","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//p[@class='font-lightgrey bold'][normalize-space()='2']\"}\n  (Session info: chrome=123.0.6312.123); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x000000010fe590c8 chromedriver + 4595912\n1   chromedriver                        0x000000010fe50e33 chromedriver + 4562483\n2   chromedriver                        0x000000010fa5439a chromedriver + 381850\n3   chromedriver                        0x000000010fa9df08 chromedriver + 683784\n4   chromedriver                        0x000000010fa9e191 chromedriver + 684433\n5   chromedriver                        0x000000010fae2b14 chromedriver + 965396\n6   chromedriver                        0x000000010fac016d chromedriver + 823661\n7   chromedriver                        0x000000010fae014d chromedriver + 954701\n8   chromedriver                        0x000000010fabfee3 chromedriver + 823011\n9   chromedriver                        0x000000010fa90be4 chromedriver + 629732\n10  chromedriver                        0x000000010fa9179e chromedriver + 632734\n11  chromedriver                        0x000000010fe1efe2 chromedriver + 4358114\n12  chromedriver                        0x000000010fe23c2d chromedriver + 4377645\n13  chromedriver                        0x000000010fe235a3 chromedriver + 4375971\n14  chromedriver                        0x000000010fe23ed5 chromedriver + 4378325\n15  chromedriver                        0x000000010fe08a05 chromedriver + 4266501\n16  chromedriver                        0x000000010fe2425d chromedriver + 4379229\n17  chromedriver                        0x000000010fdfb050 chromedriver + 4210768\n18  chromedriver                        0x000000010fe41a98 chromedriver + 4500120\n19  chromedriver                        0x000000010fe41c11 chromedriver + 4500497\n20  chromedriver                        0x000000010fe50a73 chromedriver + 4561523\n21  libsystem_pthread.dylib             0x00007ff816bfb18b _pthread_start + 99\n22  libsystem_pthread.dylib             0x00007ff816bf6ae3 thread_start + 15","time":{"start":1713142956561,"stop":1713142974185,"duration":17624}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('setup')"]},"source":"9d55426966bcbda0.json","parameterValues":[]}